CREATE TABLE User (
	uId			BIGINT			PRIMARY KEY AUTO_INCREMENT,
	uNickName	VARCHAR(10)		NOT NULL,
	passwd		VARCHAR(10)		NOT NULL,
	uLink		VARCHAR(50)		NOT NULL,
	regDate		TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP
)AUTO_INCREMENT = 101;

CREATE TABLE Guest (
	gId			BIGINT			PRIMARY KEY AUTO_INCREMENT,
	gNickName	VARCHAR(10)		NOT NULL,
	message		VARCHAR(100)	NOT NULL,
	gift		VARCHAR(50)		NOT NULL,
	regDate		TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	
	CONSTRAINT Guest_gId
		FOREIGN KEY(gId) REFERENCES User(uId)
)AUTO_INCREMENT = 1001;